CREATE TABLE workspaces (
    id UUID PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_workspaces_modtime 
BEFORE UPDATE ON workspaces 
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();
